Milosev domaci
Marko-91/generacija-qa-14 pull request #1
Opened 2022-10-03 19:50 UTC by TheBlackbird95

Dodao sam domaci

2022-10-03 19:56 UTC, Marko-91 requested changes

2022-10-03 19:56 UTC, Marko-91 commented on src/com/itbootcamp/bgqa/nedelja7/domaci/D_19_Milos_Kos.java
> +        assert prosao.isDisplayed();
Zasto ovde nismo koristili testNG Assert.true() ?
```suggestion
        Assert.assertTrue(prosao.isDisplayed());
```

2022-10-03 19:56 UTC, Marko-91 commented on src/com/itbootcamp/bgqa/nedelja7/domaci/D_19_Milos_Kos.java
> +        Thread.sleep(3000);
Zasto nam treba sleep?

2022-10-03 19:56 UTC, Marko-91 commented on src/com/itbootcamp/bgqa/nedelja7/domaci/D_19_Milos_Kos.java
> +        System.setProperty("webdriver.chrome.driver",
Bolje koristi prop reader

2022-10-04 17:11 UTC, TheBlackbird95 commented on src/com/itbootcamp/bgqa/nedelja7/domaci/D_19_Milos_Kos.java
> +        Thread.sleep(3000);
Zato sto ni jedan drugi sleep nije radio posao :(

2022-10-04 17:28 UTC, Marko-91 approved these changes

2022-10-04 17:30 UTC, Marko-91 commented
Sve ok

2022-10-04 17:30 UTC, merged